# Generated by Django 3.1 on 2020-08-22 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=5, unique=True)),
                ('state', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'short_name')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, unique=True, verbose_name='Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('job', models.CharField(choices=[('0', 'Accountant'), ('1', 'Administrator'), ('2', 'Economist'), ('3', 'Programmer'), ('4', 'Others')], max_length=20)),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.departament')),
                ('skill', models.ManyToManyField(to='employee.Skill')),
            ],
            options={
                'ordering': ['last_name'],
                'unique_together': {('first_name', 'last_name', 'job')},
            },
        ),
    ]
